services:

  subscription-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: subscription-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Coti@2026
    ports:
      - "1434:1433"
    networks:
      - subscription-network
    volumes:
      - sqlserver-data:/var/opt/mssql

  subscription-rabbitmq:
    image: rabbitmq:3-management
    container_name: subscription-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672" 
      - "15672:15672"
    networks:
      - subscription-network
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

networks:
  subscription-network:
    driver: bridge

volumes:
  sqlserver-data:
  rabbitmq-data: